### PR TITLE
 Fixed db join call

### PR DESCRIPTION
**Pull request by builder-247**

### CODE REVIEW

**Comment by howardchung** [comment]
you need to rebase to fix the conflicts

**Comment by howardchung** [comment]
there still seem to  be unrelated changes to manifest and package?

**Comment by builder-247** [comment]
> there still seem to be unrelated changes to manifest and package?

Rebasing got me here. There are no conflicts and the changes are par with master right?

**Comment by howardchung** [comment]
Looks like it merged OK, although I'm not sure what makes GitHub think there are 21 commits and 4 file changes. I'd advise deleting your dev branch and syncing to master to avoid this issue in the future.

**Pull request merged**
