### PR TITLE
Upgrade eslint, apply lint fixes, add lint github action

### PR DESCRIPTION
**Pull request by ff137**
Upgraded eslint + config + prettier dependencies with the following:
```sh
npm install --save-dev eslint@latest prettier@latest eslint-config-prettier@latest eslint-plugin-import@latest eslint-config-airbnb@latest
```

Fixed linting errors where possible and added ignores otherwise

Added lint job to github actions

### CODE REVIEW

**Comment by ff137** [comment]
Running the lint script with `npm run lint` yields the errors. 
Some can be fixed automatically, but I'll go through these until linting passes.

```sh
$ npm run lint

> opendota-core@21.0.2 lint
> eslint . --ext .js,.jsx --ignore-path .gitignore


/root/dev/ff137/core/dev/cassandraRandom.js
  13:74  error  Parsing error: Unexpected token .

/root/dev/ff137/core/dev/cassandraTest.js
  11:58  error  Unary operator '++' used          no-plusplus
  13:22  error  Unexpected `await` inside a loop  no-await-in-loop

/root/dev/ff137/core/index.js
  15:5  error  Strings must use doublequote  quotes

/root/dev/ff137/core/routes/generateOperationId.js
   1:1  error  Expected exception block, space or tab after '/*' in comment  spaced-comment
  23:7  error  Unexpected string concatenation                               prefer-template

/root/dev/ff137/core/routes/keyManagement.js
  98:46  error  Parsing error: Unexpected token .

/root/dev/ff137/core/routes/requests/importParams.js
  18:25  error  Calls to require() should use string literals  import/no-dynamic-require
  18:25  error  Unexpected require()                           global-require

/root/dev/ff137/core/routes/responses/schemas/hero/HeroStatsResponse.js
  134:42  error  Expected exception block, space or tab after '//' in comment  spaced-comment
  219:7   error  Expected exception block, space or tab after '//' in comment  spaced-comment

/root/dev/ff137/core/routes/responses/schemas/importResponseSchemas.js
  18:25  error  Calls to require() should use string literals  import/no-dynamic-require
  18:25  error  Unexpected require()                           global-require

/root/dev/ff137/core/routes/responses/schemas/player/PlayerCountsResponse.js
  1:7  error  'commonProperties' is assigned a value but never used  no-unused-vars

/root/dev/ff137/core/routes/spec.js
  202:67  error  Parsing error: Unexpected token .

/root/dev/ff137/core/scripts/convertSpec.js
  2:22  error  Unexpected use of file extension "js" for "../routes/spec.js"  import/extensions

/root/dev/ff137/core/store/buildMatch.js
  82:40  error  Parsing error: Unexpected token .

/root/dev/ff137/core/store/queries.js
  1706:36  error  Parsing error: Unexpected token .

/root/dev/ff137/core/svc/apiadmin.js
  102:5   error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
  103:7   error  Unary operator '++' used                                                                                                                                                   no-plusplus
  115:9   error  Unexpected use of continue statement                                                                                                                                       no-continue
  152:19  error  Strings must use doublequote                                                                                                                                               quotes
  168:16  error  Unexpected function expression                                                                                                                                             prefer-arrow-callback
  193:16  error  Unexpected function expression                                                                                                                                             prefer-arrow-callback

/root/dev/ff137/core/svc/cassandraDelete.js
  11:74  error  Parsing error: Unexpected token .

/root/dev/ff137/core/svc/fullhistory.js
  6:7  error  'constants' is assigned a value but never used  no-unused-vars

/root/dev/ff137/core/svc/livegames.js
  9:9  error  'invokeInterval' is assigned a value but never used  no-unused-vars

/root/dev/ff137/core/svc/parser.js
  67:10  error  Expected to return a value at the end of function 'parseProcessor'  consistent-return

/root/dev/ff137/core/svc/retriever.js
  440:10  error  Unnecessary 'else' after 'return'  no-else-return

/root/dev/ff137/core/svc/scenariosCleanup.js
  37:8  error  'cb' is defined but never used                         no-unused-vars
  38:1  error  This line has a length of 181. Maximum allowed is 180  max-len

/root/dev/ff137/core/svc/skill.js
  8:7  error  'queries' is assigned a value but never used  no-unused-vars

/root/dev/ff137/core/svc/syncSubs.js
   7:16  error  `stripe` import should occur before import of `../store/db`                                                                                                                import/order
  11:20  error  'cb' is defined but never used                                                                                                                                             no-unused-vars
  14:3   error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
  25:38  error  Unary operator '++' used                                                                                                                                                   no-plusplus
  28:5   error  Unexpected `await` inside a loop                                                                                                                                           no-await-in-loop

/root/dev/ff137/core/svc/web.js
  318:17  error  Parsing error: Unexpected token .

/root/dev/ff137/core/test/test.js
  437:35  error  Parsing error: Unexpected token .

/root/dev/ff137/core/util/getGcData.js
  21:26  error  Parsing error: Unexpected token .

/root/dev/ff137/core/util/utility.js
  464:36  error  Unary operator '++' used  no-plusplus

✖ 45 problems (45 errors, 0 warnings)
  9 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by ff137** [comment]
Quite a few of those errors (such as `Parsing error: Unexpected token .`) are due to linter not knowing the javascript version being used. To fix that, I added the following to the `.eslintrc.json`:
```json
  "parserOptions": {
    "ecmaVersion": 2023
  },
```

Now there are 181 problems ... 104 of which are automatically fixable.

**Comment by ff137** [comment]
Ok, with the help of Cursor (VS Code with ChatGPT), I was able to fix most of the linting errors that remained. 

Some nice improvements include replacing await in a loop with executing all promises concurrently. The other changes are fairly trivial. 

There's a few cases where I couldn't figure out how to replace the await in a loop.
In `svc/cassandraDelete.js` and `dev/cassandraRandom.js`, there is a `while(true)` loop that contains await commands. No idea how to unravel that, so I'm leaving it as is.

**Comment by ff137** [comment]
So, my renaming of variables (from snake_case to camelCase) broke something in keyManagement/tests, so rolling back those changes

I notice that test are actually quite sparse in this repo (no tests for routes), so with this refactoring it may be worthwhile if I include some more tests to make sure I didn't break anything else with the linting changes.

**Comment by howardchung** [comment]
I'm going to revisit eslint later--I think typescript helps us catch most of the important kinds of errors

**Pull request closed without merging**
